config/routes.rb
Rails.application.routes.draw do
  root 'flights#index'
  resources :flights, only: [:index]
  resources :bookings, only: [:new, :create]

end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, class_name: 'Flight', foreign_key: 'departure_airport_id'
  has_many :arriving_flights, class_name: 'Flight', foreign_key: 'arrival_airport_id'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: 'Airport', foreign_key: 'departure_airport_id'
  belongs_to :arrival_airport, class_name: 'Airport', foreign_key: 'arrival_airport_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    # Assuming booking will require user information next
    @flight = Flight.find(params[:flight_id])
    @num_tickets = params[:num_tickets].to_i
    # Setup for new booking will go here
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    # Retrieve all airports for the search form dropdowns
    @airports = Airport.all
    @num_tickets = params[:num_tickets]

    # Handle search parameters if present
    if params[:departure_airport_id] && params[:arrival_airport_id] && params[:date]
      date = Date.parse(params[:date])
      # Narrow down the search to the specific day regardless of time
      start_datetime = date.beginning_of_day
      end_datetime = date.end_of_day

      @flights = Flight.where(departure_airport_id: params[:departure_airport_id],
                              arrival_airport_id: params[:arrival_airport_id],
                              start_datetime: start_datetime..end_datetime)
    else
      @flights = []
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/index.html.erb
<h1>Search for Flights</h1>
<%= form_with url: flights_path, method: :get, local: true do |form| %>
  <%= form.collection_select :departure_airport_id, @airports, :id, :code, prompt: 'Select Departure Airport' %>
  <%= form.collection_select :arrival_airport_id, @airports, :id, :code, prompt: 'Select Arrival Airport' %>
  <%= form.date_select :date, start_date: Date.today, end_date: 1.year.from_now, discard_day: true %>
  <%= form.select :num_tickets, options_for_select(1..4), prompt: "Number of Passengers" %>
  <%= form.submit 'Find Flights' %>
<% end %>

<% if @flights.any? %>
  <h2>Select a Flight</h2>
  <%= form_with url: new_booking_path, method: :get do |form| %>
    <% @flights.each do |flight| %>
      <div>
        <%= form.radio_button :flight_id, flight.id %>
        <%= label_tag "flight_#{flight.id}", "Departure: #{flight.start_datetime}, Duration: #{flight.duration} minutes" %>
      </div>
    <% end %>
    <%= form.hidden_field :num_tickets, value: @num_tickets %>
    <%= form.submit 'Book Flight' %>
  <% end %>
<% else %>
  <p>No flights match your search criteria.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>